import os
import sys

BIN_DIR=os.environ['BIN_DIR'];
GTEST_ROOT=os.environ['GTEST_ROOT'];
APP_SRC_ROOT=os.environ['SRC_DIR'];

env=DefaultEnvironment().Clone();

INCLUDE_PATH = [
  GTEST_ROOT,
  APP_SRC_ROOT,
  os.path.join(GTEST_ROOT, 'src'),
  os.path.join(GTEST_ROOT, 'include'),
  os.path.join(GTEST_ROOT, 'make')]

env['CPPPATH'] = INCLUDE_PATH
env['LIBS'] = ['compiler', 'interpreter', 'parser', 'base'] + env['LIBS']

SOURCES = [
 os.path.join(GTEST_ROOT, 'src/gtest-all.cc'),
] + Glob('*.cc') + Glob('*.c')

env.Program(os.path.join(BIN_DIR, 'runTest'), SOURCES);


